create table if not exists application_data(
SK_ID_CURR bigint unique,
TARGET bigint,
NAME_CONTRACT_TYPE text,
CODE_GENDER text,
FLAG_OWN_CAR text,
FLAG_OWN_REALTY text,
CNT_CHILDREN bigint,
AMT_INCOME_TOTAL double precision,
AMT_CREDIT double precision,
AMT_ANNUITY double precision,
AMT_GOODS_PRICE double precision,
NAME_TYPE_SUITE text,
NAME_INCOME_TYPE text,
NAME_EDUCATION_TYPE text,
NAME_FAMILY_STATUS text,
NAME_HOUSING_TYPE text,
REGION_POPULATION_RELATIVE double precision,
DAYS_BIRTH bigint,
DAYS_EMPLOYED bigint,
DAYS_REGISTRATION double precision,
DAYS_ID_PUBLISH bigint,
OWN_CAR_AGE double precision,
FLAG_MOBIL bigint,
FLAG_EMP_PHONE bigint,
FLAG_WORK_PHONE bigint,
FLAG_CONT_MOBILE bigint,
FLAG_PHONE bigint,
FLAG_EMAIL bigint,
OCCUPATION_TYPE text,
CNT_FAM_MEMBERS double precision,
REGION_RATING_CLIENT bigint,
REGION_RATING_CLIENT_W_CITY bigint,
WEEKDAY_APPR_PROCESS_START text,
HOUR_APPR_PROCESS_START bigint,
REG_REGION_NOT_LIVE_REGION bigint,
REG_REGION_NOT_WORK_REGION bigint,
LIVE_REGION_NOT_WORK_REGION bigint,
REG_CITY_NOT_LIVE_CITY bigint,
REG_CITY_NOT_WORK_CITY bigint,
LIVE_CITY_NOT_WORK_CITY bigint,
ORGANIZATION_TYPE text,
EXT_SOURCE_1 double precision,
EXT_SOURCE_2 double precision,
EXT_SOURCE_3 double precision,
APARTMENTS_AVG double precision,
BASEMENTAREA_AVG double precision,
YEARS_BEGINEXPLUATATION_AVG double precision,
YEARS_BUILD_AVG double precision,
COMMONAREA_AVG double precision,
ELEVATORS_AVG double precision,
ENTRANCES_AVG double precision,
FLOORSMAX_AVG double precision,
FLOORSMIN_AVG double precision,
LANDAREA_AVG double precision,
LIVINGAPARTMENTS_AVG double precision,
LIVINGAREA_AVG double precision,
NONLIVINGAPARTMENTS_AVG double precision,
NONLIVINGAREA_AVG double precision,
APARTMENTS_MODE double precision,
BASEMENTAREA_MODE double precision,
YEARS_BEGINEXPLUATATION_MODE double precision,
YEARS_BUILD_MODE double precision,
COMMONAREA_MODE double precision,
ELEVATORS_MODE double precision,
ENTRANCES_MODE double precision,
FLOORSMAX_MODE double precision,
FLOORSMIN_MODE double precision,
LANDAREA_MODE double precision,
LIVINGAPARTMENTS_MODE double precision,
LIVINGAREA_MODE double precision,
NONLIVINGAPARTMENTS_MODE double precision,
NONLIVINGAREA_MODE double precision,
APARTMENTS_MEDI double precision,
BASEMENTAREA_MEDI double precision,
YEARS_BEGINEXPLUATATION_MEDI double precision,
YEARS_BUILD_MEDI double precision,
COMMONAREA_MEDI double precision,
ELEVATORS_MEDI double precision,
ENTRANCES_MEDI double precision,
FLOORSMAX_MEDI double precision,
FLOORSMIN_MEDI double precision,
LANDAREA_MEDI double precision,
LIVINGAPARTMENTS_MEDI double precision,
LIVINGAREA_MEDI double precision,
NONLIVINGAPARTMENTS_MEDI double precision,
NONLIVINGAREA_MEDI double precision,
FONDKAPREMONT_MODE text,
HOUSETYPE_MODE text,
TOTALAREA_MODE double precision,
WALLSMATERIAL_MODE text,
EMERGENCYSTATE_MODE text,
OBS_30_CNT_SOCIAL_CIRCLE double precision,
DEF_30_CNT_SOCIAL_CIRCLE double precision,
OBS_60_CNT_SOCIAL_CIRCLE double precision,
DEF_60_CNT_SOCIAL_CIRCLE double precision,
DAYS_LAST_PHONE_CHANGE double precision,
FLAG_DOCUMENT_2 bigint,
FLAG_DOCUMENT_3 bigint,
FLAG_DOCUMENT_4 bigint,
FLAG_DOCUMENT_5 bigint,
FLAG_DOCUMENT_6 bigint,
FLAG_DOCUMENT_7 bigint,
FLAG_DOCUMENT_8 bigint,
FLAG_DOCUMENT_9 bigint,
FLAG_DOCUMENT_10 bigint,
FLAG_DOCUMENT_11 bigint,
FLAG_DOCUMENT_12 bigint,
FLAG_DOCUMENT_13 bigint,
FLAG_DOCUMENT_14 bigint,
FLAG_DOCUMENT_15 bigint,
FLAG_DOCUMENT_16 bigint,
FLAG_DOCUMENT_17 bigint,
FLAG_DOCUMENT_18 bigint,
FLAG_DOCUMENT_19 bigint,
FLAG_DOCUMENT_20 bigint,
FLAG_DOCUMENT_21 bigint,
AMT_REQ_CREDIT_BUREAU_HOUR double precision,
AMT_REQ_CREDIT_BUREAU_DAY double precision,
AMT_REQ_CREDIT_BUREAU_WEEK double precision,
AMT_REQ_CREDIT_BUREAU_MON double precision,
AMT_REQ_CREDIT_BUREAU_QRT double precision,
AMT_REQ_CREDIT_BUREAU_YEAR double precision
);

create table if not exists previous_application(
SK_ID_PREV bigint,
SK_ID_CURR bigint unique,
NAME_CONTRACT_TYPE text,
AMT_ANNUITY double precision,
AMT_APPLICATION double precision,
AMT_CREDIT double precision,
AMT_DOWN_PAYMENT double precision,
AMT_GOODS_PRICE double precision,
WEEKDAY_APPR_PROCESS_START text,
HOUR_APPR_PROCESS_START bigint,
FLAG_LAST_APPL_PER_CONTRACT text,
NFLAG_LAST_APPL_IN_DAY bigint,
RATE_DOWN_PAYMENT double precision,
RATE_INTEREST_PRIMARY double precision,
RATE_INTEREST_PRIVILEGED double precision,
NAME_CASH_LOAN_PURPOSE text,
NAME_CONTRACT_STATUS text,
DAYS_DECISION bigint,
NAME_PAYMENT_TYPE text,
CODE_REJECT_REASON text,
NAME_TYPE_SUITE text
);

alter table previous_application 
add constraint fk_prev_app_data 
foreign key (SK_ID_CURR) references application_data (SK_ID_CURR);