create table if not exists application_data(
SK_ID_PREV bigint,
SK_ID_CURR bigint,
NAME_CONTRACT_TYPE text,
AMT_ANNUITY double precision,
AMT_APPLICATION double precision,
AMT_CREDIT double precision,
AMT_DOWN_PAYMENT double precision,
AMT_GOODS_PRICE double precision,
WEEKDAY_APPR_PROCESS_START text,
HOUR_APPR_PROCESS_START bigint,
FLAG_LAST_APPL_PER_CONTRACT text,
NFLAG_LAST_APPL_IN_DAY bigint,
RATE_DOWN_PAYMENT double precision,
RATE_INTEREST_PRIMARY double precision,
RATE_INTEREST_PRIVILEGED double precision,
NAME_CASH_LOAN_PURPOSE text,
NAME_CONTRACT_STATUS text,
DAYS_DECISION bigint,
NAME_PAYMENT_TYPE text,
CODE_REJECT_REASON text,
NAME_TYPE_SUITE text,
NAME_CLIENT_TYPE text,
NAME_GOODS_CATEGORY text,
NAME_PORTFOLIO text,
NAME_PRODUCT_TYPE text,
CHANNEL_TYPE text,
SELLERPLACE_AREA bigint,
NAME_SELLER_INDUSTRY text,
CNT_PAYMENT double precision,
NAME_YIELD_GROUP text,
PRODUCT_COMBINATION text,
DAYS_FIRST_DRAWING double precision,
DAYS_FIRST_DUE double precision,
DAYS_LAST_DUE_1ST_VERSION double precision,
DAYS_LAST_DUE double precision,
DAYS_TERMINATION double precision,
NFLAG_INSURED_ON_APPROVAL double precision,
);

alter table previous_application
add constraint fk_prev_app_data
foreign key (SK_ID_CURR) references application_data (SK_ID_CURR);
